packages:
  - 'apps/*'
  - 'packages/*'
  - 'workers/*'
  - 'database'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  prisma: true
  sharp: true
